server:
  port: 8888

spring:
  profiles:
    active: dev
  datasource:
    druid:
      max-wait: 10000
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://yhocn.cn/zhuxiang?autoReconnect=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: Lyh07910
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# nohup java -jar xx.jar
# ps aux|grep jar
# 111 xxx xxx xxx  xxx xx.jar
# kill -9 进程号

# java -jar xx.jar
